# cloudbuild.yaml — Build & Deploy FE (Streamlit) lên Cloud Run
# Kích hoạt khi push lên branch main (dùng Cloud Build Trigger)

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  # --- Có thể override trong Cloud Build Trigger nếu muốn ---
  _REGION: "asia-southeast1"
  _SERVICE_NAME: "invoice-fe"
  _REPO_NAME: "invoice-fe-repo"
  _BACKEND_URL: "https://invoice-pipeline-160913806.asia-southeast1.run.app"

steps:
  # 0) Bật Docker AR repo nếu lỡ chưa có (idempotent)
  - name: gcr.io/cloud-builders/gcloud
    id: ensure-repo
    entrypoint: bash
    args:
      - -lc
      - |
        set -e
        if ! gcloud artifacts repositories describe "$_REPO_NAME" --location="$_REGION" >/dev/null 2>&1; then
          gcloud artifacts repositories create "$_REPO_NAME" \
            --repository-format=docker \
            --location="$_REGION" \
            --description="Repo for Streamlit FE"
        fi

  # 1) Build & push image
  - name: gcr.io/cloud-builders/docker
    id: build-and-push
    args:
      - build
      - "-t"
      - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/streamlit-fe:$SHORT_SHA"
      - "-t"
      - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/streamlit-fe:latest"
      - "."

  - name: gcr.io/cloud-builders/docker
    id: push-latest
    args: ["push", "asia-southeast1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/streamlit-fe:latest"]

  - name: gcr.io/cloud-builders/docker
    id: push-sha
    args: ["push", "asia-southeast1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/streamlit-fe:$SHORT_SHA"]

  # 2) Deploy Cloud Run (public)
  - name: gcr.io/cloud-builders/gcloud
    id: deploy
    args:
      - run
      - deploy
      - "$_SERVICE_NAME"
      - "--image=asia-southeast1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/streamlit-fe:$SHORT_SHA"
      - "--region=$_REGION"
      - "--allow-unauthenticated"
      - "--port=8080"
      - "--memory=512Mi"
      - "--max-instances=5"
      - "--set-env-vars=BACKEND_URL=$_BACKEND_URL,STREAMLIT_SERVER_HEADLESS=true,STREAMLIT_BROWSER_GATHER_USAGE_STATS=false"

images:
  - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/streamlit-fe:$SHORT_SHA"
  - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/streamlit-fe:latest"
