substitutions:
  _REGION: "asia-southeast1"
  _REPO: "invoice-pipeline"
  _SERVICE: "invoice-fe"
  _PORT: "8080"

steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build image"
    args:
      - build
      - -f
      - fe/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA
      - fe

  - name: "gcr.io/cloud-builders/docker"
    id: "Push image"
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy to Cloud Run"
    entrypoint: gcloud
    args:
      [
        "run","deploy","${_SERVICE}",
        "--image","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA",
        "--region","${_REGION}",
        "--allow-unauthenticated",
        "--platform","managed",
        "--port","${_PORT}"
      ]

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA
