[theme]
primaryColor = "#4F46E5" # Màu tím than Indigo (Rất trendy)
backgroundColor = "#F3F4F6" # Màu nền xám nhạt (để làm nổi các card trắng)
secondaryBackgroundColor = "#E5E7EB"
textColor = "#1F2937"
font = "sans serif"
